### N维数组是机器学习和神经网络的主要数据结构
- 0—d 标量 一个类别
- 1—d向量 一个特征向量
- 2—d 矩阵 一个特征矩阵
- 3—d RGB图片（宽x高x通道）
- 4—d 视频 一个RGB通道的batch
### 创建数组需要
- 形状
- 数据类型
- 每个元素的值


In [1]:
import torch

张量表示数值组成的数组，可能有多个维度

In [3]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape #访问张量的形状

torch.Size([12])

In [5]:
x.numel() #访问张量的元素总数

12

In [ ]:
X=x.reshape(3,4) #改变张量的形状但不改变数量和元素值
X

In [7]:
torch.zeros(size=(2,3,4)) #创建全0张量
#torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
print(torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1),sep='\n')
#张量的连接,其中0维表示行，1维表示列
#对于二维的数组来说，dim=0进行数据的拼接，dim=1进行标签的扩展

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [12]:
X==Y #张量的逻辑运算
#返回对应的布尔值形成的张量

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
X.sum() #张量的元素求和
#返回一个只有一个元素的张量
#数字后的点表示这是浮点数

tensor(66.)

#### 即使形状不同，仍然可以通过广播机制来执行元素操作

In [15]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
print(a+b)
#广播机制可能会导致一些难以发现的错误
#形状不对仍能正常运行

tensor([[0, 1],
        [1, 2],
        [2, 3]])


#### 运行一些操作可能会为新结果分配内存

In [ ]:
before=id(Y)
Y=Y+X
id(Y)==before

#### 执行原地操作

In [19]:
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 5061169296
id(Z): 5061169296


#### 转换为numpy张量

In [22]:
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

#### 将大小为1的张量转换为python标量

In [23]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)