### 标量用只有一个的张量表示

In [1]:
import torch
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

### 可以把向量当作标量组成的列表

In [2]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [3]:
print(x[3],x.shape,len(x))

tensor(3) torch.Size([4]) 4


### 通过指定两个分量m和n来创建一个mxn矩阵

In [4]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [5]:
A.T#矩阵的转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

### 给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [7]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
#而如果直接赋值，只是给到了对应的索引
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [8]:
#两个矩阵的按元素乘法称为哈达玛积
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

### 计算其元素的和

In [9]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

### 表示任意形状张量的元素和

In [12]:
A.shape, A.sum()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [13]:
A_sum_axis0 = A.sum(axis=0)
print(A)
A_sum_axis0, A_sum_axis0.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor([40., 45., 50., 55.]), torch.Size([4]))

### 计算总和或均值时保持轴数不变

In [15]:
print(A.sum(axis=1,keepdim=True))
print(A.sum(axis=1))

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
tensor([ 6., 22., 38., 54., 70.])


### 矩阵乘法

In [19]:
A=torch.arange(20).reshape(5,4)
B=torch.arange(24).reshape(4,6)
print(A)
print(B)
print(torch.mm(A,B))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
tensor([[  84,   90,   96,  102,  108,  114],
        [ 228,  250,  272,  294,  316,  338],
        [ 372,  410,  448,  486,  524,  562],
        [ 516,  570,  624,  678,  732,  786],
        [ 660,  730,  800,  870,  940, 1010]])


### 矩阵的L2范数

In [20]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)