In [2]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

### 在计算梯度之前，需要一个地方来存储梯度

In [4]:
x.requires_grad_(True) #等价于x=torch.arange(4.0,requires_grad=True)
x.grad

### 现在计算y

In [5]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

### 通过调用反向传播函数来自动计算y关于x每个分量的梯度，并打印这些梯度

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

### 现在计算x的另一个函数

In [7]:
# 在默认情况下，pytorch会累积梯度，我们需要清除之前的值
#pytorch中带下划线的函数表示进行原地操作
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 将某些计算移动到记录的计算图之外

In [9]:
x.grad.zero_()
y=x*x
u=y.detach()
#此时u被移出计算图外，是一个数值等于x*x的常数
z=u*x

z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [11]:
#调用前清零的习惯
x.grad.zero_()
y.sum().backward()
x.grad==2*x

tensor([True, True, True, True])

### 即使构建函数的计算图需要通过python控制流（例如，条件、循环或任意函数调用），我们仍然可以计算得到的变量的梯度

In [ ]:
def f(a):
    b=a*2
    while b.norm()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b